version: '3.8'

services:
  trabalho03-linux:
    build: .
    container_name: trabalho03-streaming-edu
    ports:
      - "8080:80"
    volumes:
      - ./scripts:/app/scripts
      - ./source:/app/source
    stdin_open: true
    tty: true