services:
  streaming-env:
    build: .
    container_name: trabalho03-streaming-edu
    ports:
      - "8080:80"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
    command: tail -f /dev/null